// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    apply from: 'versions.gradle'
}

plugins {
    id 'com.android.application' version '8.6.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
    id 'org.jetbrains.kotlin.kapt' version '2.2.20'  apply false
    id("org.jetbrains.kotlin.plugin.serialization") version "2.2.20"  apply false
    // Apply the Kotlin Compose plugin
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.0'  apply false

    id 'androidx.navigation.safeargs.kotlin' version '2.9.5'  apply false
    // Apply the Crashlytics Gradle plugin
    id 'com.google.firebase.crashlytics' version '2.9.4'  apply false
    // Apply the Performance Monitoring plugin
    id 'com.google.firebase.firebase-perf' version '1.4.2'  apply false
    // Add the dependency for the Google services Gradle plugin
    id("com.google.gms.google-services") version "4.4.3" apply false
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
